name: power                                       
channels:                                                                    
  - defaults                                                             
dependencies:                                                                
  - numpy
  - matplotlib
  - make
  - seaborn
  - pandas=2.0.3
  - scikit-learn
  - geopandas
